FROM python:3.6-slim

ENV RASA_NLU_DOCKER="YES" \
    RASA_NLU_HOME=/app \
    RASA_NLU_PYTHON_PACKAGES=/usr/local/lib/python3.6/dist-packages

RUN apt-get update -qq \
    && apt-get install -y --no-install-recommends build-essential git-core \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

WORKDIR ${RASA_NLU_HOME}

COPY . ${RASA_NLU_HOME}

RUN pip install -r alt_requirements/requirements_bare.txt

RUN pip install -e .

RUN pip install git+https://github.com/mit-nlp/MITIE.git \
    && pip install jieba \
    && pip install numpy scipy \ 
    && pip install scikit-learn==0.19.2

VOLUME ["/app/projects", "/app/logs", "/app/data"]

EXPOSE 5000
